### ISSUE TITLE
Better logger output

### ISSUE THREAD

**Issue by ai** [wilddima/logux_rails#3]
Current output:

![7gfgqnq](https://user-images.githubusercontent.com/19343/45589748-388e0880-b8f9-11e8-98eb-08f7ff9e4c7c.png)

How we can imporve it:

1. `Write to logux` → `Write to Logux response`
2. `Searching action for action: #{action}, meta: #{meta}` → `Searching action for Logux action: #{action}, meta: #{meta}`
3. `Searching policy for action: #{action}, meta: #{meta}` → `Searching policy for Logux action: #{action}, meta: #{meta}`
4. `Logux add` → `Receive from Logux`
5. Add color to output. Use yellow for messages and JSON highlighter for JSON message in `Receive from Logux`

**Comment by wilddima** [comment]
https://github.com/wilddima/logux_rails/pull/10
