### ISSUE TITLE
strong_params для action

### ISSUE THREAD

**Issue by ai** [wilddima/logux_rails#8]
Add to Action params filtering as in Rails controllers
https://weblog.rubyonrails.org/2012/3/21/strong-parameters/

**Comment by wilddima** [comment]
For the very first implementation, we can inherit from:
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/strong_parameters.rb

**Comment by markfrst** [comment]
@wilddima I understood correctly that there must be something in the likeness:

`Logux::Actions.new(type: 'user/add', channel: 'project/123', test1: 'asd', test2: 'asd').permit(:type, :channel) # => { type: 'user/add', channel: 'project/123' }`

?

**Comment by ai** [comment]
Seems like so

**Comment by markfrst** [comment]
okay
